[package]
name = "noxfutura"
version = "0.2.0"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"

[dependencies]
wgpu = "0.6.0"
winit = { version = "0.22.2", features = ["web-sys"] }
futures = { version = "0.3" }
bengine = { path = "bengine/" }

[profile.dev]
opt-level = 1

[profile.release]
incremental = true
#lto = "thin"
#debug = true # Disable when not profiling

[workspace]
members = [ 
    "bengine",
]