[package]
name = "noxfutura"
version = "0.2.0"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"

[dependencies]
bengine = { path = "bengine/" }
bracket-random = "0.8.0"

[profile.dev]
#opt-level = 1

[profile.release]
incremental = true
#lto = "thin"
#debug = true # Disable when not profiling

[workspace]
members = [ 
    "bengine",
]