[package]
name = "noxfutura"
version = "0.2.0"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"

[dependencies]
bracket-lib = { version = "0.8" }
nox-api = { path = "nox-api/" }
bracket-ui = { path = "bracket-ui/" }

[profile.dev]
opt-level = 1

[profile.release]
#lto = "thin"
#debug = true # Disable when not profiling

[workspace]
members = [ 
    "nox-api",
    "bracket-ui"
    ]