[package]
name = "noxfutura"
version = "0.2.0"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"

[dependencies]

[profile.dev]
opt-level = 1

[profile.release]
#lto = "thin"
#debug = true # Disable when not profiling

[workspace]
members = []