[package]
name = "noxfutura"
version = "0.2.0"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"

[dependencies]
bengine = { path = "bengine/" }
bracket-random = "0.8.0"
lazy_static = "1.4.0"
parking_lot = "0.11.0"
serde = { version = "1.0.115" }
ron = "0.6.1"
Inflector = "0.11.4" # You just had to be clever with a capital letter

[profile.dev]
#opt-level = 1

[profile.release]
incremental = true
#lto = "thin"
#debug = true # Disable when not profiling

[workspace]
members = [ 
    "bengine",
]