[package]
name = "noxfutura"
version = "0.2.0"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"

[dependencies]
bengine = { path = "bengine/" }
bracket-random = "0.8.0"
bracket-geometry = { version = "0.8.1", features = ["serde"] }
bracket-noise = "0.8.1"
lazy_static = "1.4.0"
parking_lot = "0.11.0"
serde = { version = "1.0.115" }
ron = "0.6.1"
Inflector = "0.11.4" # You just had to be clever with a capital letter
cgmath = "0.17.0"
flate2 = "1.0.17"
byteorder = "1.3.4"
bracket-color = { version = "0.8.1", features = ["rex", "serde"] }
smallvec = "1.4.2"
legion = { git =  "https://github.com/TomGillen/legion", rev="d68d340c006244ddf1d53f994aa0bf4360e49336", features = [ "serialize" ] }
bincode = "1.3.1"
miniz_oxide = "0.4.1"
bytemuck = "1.4.0"

[profile.dev]
#opt-level = 1

[profile.release]
incremental = true
#lto = "thin"
#debug = true # Disable when not profiling

[workspace]
members = [ 
    "bengine",
]