[package]
name = "noxfutura"
version = "0.1.0"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"

[dependencies]
wgpu = { version = "0.5.0" }
winit = { version = "0.21.0", features = ["web-sys"] }
futures = "0.3"
env_logger = "0.7"
glsl-to-spirv = "0.1.7"
imgui = "0.3.0"
imgui-wgpu = "0.6.0"
imgui-winit-support = { version = "0.3", default-features = false, features = [ "winit-20" ] }
