[package]
name = "noxfutura"
version = "0.1.0"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"

[dependencies]
nox_raws = { path = "nox_raws" }
nox_components = { path = "nox_components" }

wgpu = { version = "0.5.0" }
winit = { version = "0.22.2", features = ["web-sys"] }
futures = "0.3"
glsl-to-spirv = "0.1.7"
imgui = "0.4.0"
imgui-wgpu = "0.7.0"
imgui-winit-support = { version = "0.4", default-features = false, features = [ "winit-22" ] }
bytemuck = "1.2.0"
image = "0.23.6"
failure = "0.1"
ultraviolet = "0.4.6"
bracket-random = { version = "0.8.0", default-features = false }
bracket-noise = "0.8.1"
bracket-geometry = { version = "0.8.1", features = ["serde"] }
bracket-color = { version = "0.8.1", features = ["rex", "serde"] }
lazy_static = "1.4.0"
parking_lot = "0.11.0"
serde = { version = "1.0.114" }
miniz_oxide = "0.4.0"
bincode = "1.3.1"
zerocopy = "0.3.0"

legion = { git = "https://github.com/TomGillen/legion", features = [ "serialize" ]}
type-uuid = "0.1"
erased-serde = "0.3"
uuid = { version = "0.8", features = ["v4"] }

rayon = "1.3.1"
flate2 = "1.0.16"
byteorder = "1.3.4"

dot_vox = "4.1.0"

[profile.dev]
opt-level = 1

[profile.release]
#incremental = true

#[profile.release]
#lto = true

[workspace]
members = [
    "nox_raws",
    "nox_components"
]