[package]
name = "noxfutura"
version = "0.1.0"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"

[dependencies]
wgpu = { version = "0.5.0" }
winit = { version = "0.21.0", features = ["web-sys"] }
futures = "0.3"
glsl-to-spirv = "0.1.7"
imgui = "0.3.0"
imgui-wgpu = "0.6.0"
imgui-winit-support = { version = "0.3", default-features = false, features = [ "winit-20" ] }
bytemuck = "1.2.0"
image = "0.22"
failure = "0.1"
ultraviolet = "0.4.6"
bracket-random = "0.8.0"
bracket-noise = "0.8.1"
bracket-geometry = { version = "0.8.1", features = ["serde"] }
lazy_static = "1.4.0"
parking_lot = "0.10.0"
serde = { version = "1.0.106" }
ron = "0.6.0"
flate2 = "1.0.14"

[profile.dev]
opt-level = 1